image: openjdk:21-jdk

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/
    - build/

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build -x test

test:
  stage: test
  script:
    - ./gradlew installPlaywrightBrowsers
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/reports/
      - build/test-results/
      - "*.png"
      - trace.zip
    expire_in: 1 week
